name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.6 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.3.6
  flutter_vibrate: ^1.3.0
  freezed: ^2.4.1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: 5.3.1
  flutter_lints: 2.0.1
  flutter_gen_runner: 5.3.1
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
