name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  shake: ^2.1.0
  audioplayers: ^0.20.1
  flutter_tts: ^3.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  assets:
    - images/magic_ball.png
    - sounds/
  uses-material-design: true
